// S14.1 — emit the committed token artifacts from the ONE authored form (src/tokens.ts).
//
// Run by `make generate`; drift is caught by `make generate-check`, exactly as api.d.ts and rbac-policy.json
// already are. That is the point: configs consume CSS and JSON, never TypeScript, so none of the
// module-resolution problems that plague config-time TS imports can occur.
import { writeFileSync } from "node:fs";
import { themeCss, scaleCss, tailwindColors, TYPOGRAPHY, SPACING, TYPE_SCALE, RADIUS, ELEVATION, MOTION } from "../dist/tokens.js";

const banner = "/* GENERATED by packages/shared/scripts/emit-tokens.mjs from src/tokens.ts — DO NOT EDIT. */\n";
writeFileSync(new URL("../generated/tokens.css", import.meta.url), banner + themeCss() + "\n" + scaleCss() + "\n");
writeFileSync(
  new URL("../generated/tokens.palette.json", import.meta.url),
  JSON.stringify({ _generated: "from packages/shared/src/tokens.ts — DO NOT EDIT", colors: tailwindColors(), fontFamily: { sans: TYPOGRAPHY.sans, mono: TYPOGRAPHY.mono }, spacing: SPACING, fontSize: TYPE_SCALE, borderRadius: RADIUS, boxShadow: ELEVATION, transitionDuration: MOTION.duration, transitionTimingFunction: MOTION.easing }, null, 2) + "\n",
);
console.log("emitted generated/tokens.css + generated/tokens.palette.json");
